name: build stage image

on:
  push:
    branches: [ main ]

env:
  buildVersion: '1.0.${{ github.run_id }}-${{ github.run_number }}'

jobs:
  build:
    name: stage image
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Print java version
        run: java -version

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set maven version
        run: mvn -B versions:set -DnewVersion=${{ env.buildVersion }}

      - name: Build jar file with mvn
        run: mvn -B verify

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.buildNumber }}',
              sha: context.sha
            })